version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
    open-pull-requests-limit: 5
    assignees:
      - "rabestro"
    reviewers:
      - "rabestro"
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "08:00"
    open-pull-requests-limit: 5
    assignees:
      - "rabestro"
    reviewers:
      - "rabestro"
    labels:
      - "ci-cd"
    commit-message:
      prefix: "chore(deps)"