plugins {
    id 'groovy'
    id 'application'
    id 'jacoco'
    id "org.sonarqube" version "7.4.0.8496"
}

group 'lv.id.jc.tracker'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Spock Framework
    testImplementation platform('org.apache.groovy:groovy-bom:5.0.8')
    testImplementation platform('org.spockframework:spock-bom:2.4-groovy-4.0')
    testImplementation 'org.spockframework:spock-core'

    // Spock Reports
    testRuntimeOnly 'com.athaydes:spock-reports:2.5.1-groovy-4.0'
    testImplementation 'org.slf4j:slf4j-api:2.0.18'
    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.18'
}

run {
    standardInput = System.in
}

application {
    mainModule = 'tracker.main'
    mainClass = 'lv.id.jc.tracker.Main'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport

    systemProperty 'com.athaydes.spockframework.report.showCodeBlocks', true
    systemProperty 'com.athaydes.spockframework.report.projectName', 'Learning Progress Tracker'
    systemProperty 'com.athaydes.spockframework.report.projectVersion', 1.0
}

jacoco {
    toolVersion = "0.8.12"
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }

    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    "**/config/*"
            ])
        }))
    }
}

sonarqube {
    properties {
        property "sonar.projectKey", "rabestro_jetbrains-academy-learning-progress-tracker"
        property "sonar.organization", "rabestro"
        property "sonar.host.url", "https://sonarcloud.io"
    }
}