### Create a new recipe "Warming Ginger Tea"
POST {{host}}/api/recipe/new
Content-Type: application/json

{
  "name": "Warming Ginger Tea",
  "category": "beverage",
  "description": "Ginger tea is a warming drink for cool weather, ...",
  "ingredients": [
    "1 inch ginger root, minced",
    "1/2 lemon, juiced",
    "1/2 teaspoon manuka honey"
  ],
  "directions": [
    "Place all ingredients in a mug and fill with warm water (not too hot so you keep the beneficial honey compounds in tact)",
    "Steep for 5-10 minutes",
    "Drink and enjoy"
  ]
}

### Create a new recipe "Fresh Mint Tea"
POST {{host}}/api/recipe/new
Content-Type: application/json

{
  "name": "Fresh Mint Tea",
  "category": "beverage",
  "description": "Light, aromatic and refreshing beverage, ...",
  "ingredients": [
    "boiled water",
    "honey",
    "fresh mint leaves"
  ],
  "directions": [
    "Boil water",
    "Pour boiling hot water into a mug",
    "Add fresh mint leaves",
    "Mix and let the mint leaves seep for 3-5 minutes",
    "Add honey and mix again"
  ]
}

### Find a recipe
GET {{host}}/api/recipe/6
Accept: application/json

### Find a recipe
GET {{host}}/api/recipe/5
Accept: application/json

### Update a recipe
PUT {{host}}/api/recipe/6
Content-Type: application/json

{
  "name": "Warming Ginger Tea",
  "category": "beverage",
  "description": "Ginger tea is a warming drink for cool weather, ...",
  "ingredients": [
    "1 inch ginger root, minced",
    "1/2 lemon, juiced",
    "1/2 teaspoon manuka honey"
  ],
  "directions": [
    "Place all ingredients in a mug and fill with warm water (not too hot so you keep the beneficial honey compounds in tact)",
    "Steep for 5-10 minutes",
    "Drink and enjoy"
  ]
}

### Delete a recipe
DELETE {{host}}/api/recipe/4

###
POST {{host}}/actuator/shutdown

### Search by category
GET {{host}}/api/recipe/search/?category=dessert

### Example 3: request with basic authentication

POST {{host}}/api/recipe/new
Authorization: Basic user1 pass1
Content-Type: application/json

{
  "name": "Mint Tea",
  "category": "beverage",
  "description": "Light, aromatic and refreshing beverage, ...",
  "ingredients": [
    "boiled water",
    "honey",
    "fresh mint leaves"
  ],
  "directions": [
    "Boil water",
    "Pour boiling hot water into a mug",
    "Add fresh mint leaves",
    "Mix and let the mint leaves seep for 3-5 minutes",
    "Add honey and mix again"
  ]
}
